# Event cuts
selections:
  event:
    event_sel: selMC
    rct: CBT
  track:
    pt_min: 0.150
    track_sel: globalTrack

# remove the jet_finder section below if jets are not needed in analysis
jet_finder:
  R: 0.4
  alg: antikt
  pT_min: 10

analysis:
  pt_min_eec: 1.0

output:
  bins:
    jet_pT: ['lin', 0, 200, 200]
    RL: ['log', 1.0e-2, 0.4, 20]
  histograms:
    jet_pT_rej: [1, "jet_pT_rej", "Jet #it{p}_{T} spectrum (rej);jet #it{p}_{T} (GeV);Counts", jet_pT]
    jet_pT_nom: [1, "jet_pT_nom", "Jet #it{p}_{T} spectrum (nom);jet #it{p}_{T} (GeV);Counts", jet_pT]
    eec_T_rej: [2, "eec_T_rej", "EEC_T (rej);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_T_nom: [2, "eec_T_nom", "EEC_T (nom);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_P_rej: [2, "eec_P_rej", "EEC_P (rej);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_P_nom: [2, "eec_P_nom", "EEC_P (nom);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_M_rej: [2, "eec_M_rej", "EEC_M (rej);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_M_nom: [2, "eec_M_nom", "EEC_M (nom);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_PM_rej: [2, "eec_PM_rej", "EEC_PM (rej);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_PM_nom: [2, "eec_PM_nom", "EEC_PM (nom);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_rej: [2, "eec_Q_rej", "EEC_Q (rej);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_nom: [2, "eec_Q_nom", "EEC_Q (nom);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
